"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert(
      "beers",
      [
        {
          id: 1,
          title: "Guinness",
          description: "Sint quis ",
          imageUrl:
            "http://irishpubchallenge.com/wp-content/uploads/2013/01/guinness.jpg",
          businessId: 1,
          categoryId: 1,
          alcohoolRate: 5,
          size: 250,
          country: "Irland",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 2,
          title: "Hoegarden",
          description: "Sint quis ",
          imageUrl:
            "http://www.beertown.net/images/catalog_images/1384229884.jpg",
          businessId: 1,
          categoryId: 1,
          alcohoolRate: 5,
          size: 250,
          country: "Belgium",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3,
          title: "Singha",
          description: "Sint quis ",
          imageUrl:
            "http://static.rcgroups.net/forums/attachments/7/2/0/9/9/a1611226-110-singha.136161615_std%5B1%5D.png?d=1197493537",
          businessId: 1,
          categoryId: 1,
          alcohoolRate: 5,
          size: 250,
          country: "Thailand",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 4,
          title: "Stella Artois",
          description: "Sint quis ",
          imageUrl:
            "http://www.adweek.com/agencyspy/files/original/stella-artois-bottle.jpg",
          businessId: 2,
          categoryId: 3,
          alcohoolRate: 5,
          size: 250,
          country: "Belgium",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 5,
          title: "Chang",
          description: "Sint quis ",
          imageUrl: "http://www.femail.com.au/graphics/changbeer1.jpg",
          businessId: 2,
          categoryId: 1,
          alcohoolRate: 5,
          size: 250,
          country: "Thailand",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 6,
          title: "Steel Reserve",
          description: "Sint quis ",
          imageUrl:
            "http://www.cherokeedistributing.com/wp-content/uploads/2012/02/Steel-Reserve.jpg",
          businessId: 2,
          categoryId: 1,
          alcohoolRate: 5,
          size: 250,
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 7,
          title: "Affligem Blonde",
          description: "Sint quis ",
          imageUrl:
            "https://www.affligembeer.com/media/1301/affligem-blond-fles-en-glas-900x900px.png?quality=75",
          businessId: 3,
          categoryId: 1,
          alcohoolRate: 5,
          size: 250,
          country: "Belgium",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 8,
          title: "Affligem Dubbel",
          description: "Sint quis ",
          imageUrl:
            "https://www.affligembeer.com/media/1303/affligem-dubbel-fles-en-glas-900x900px.png?quality=75",
          businessId: 3,
          categoryId: 2,
          alcohoolRate: 5,
          size: 250,
          country: "Belgium",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 9,
          title: "Affligem Tripel",
          description: "Sint quis ",
          imageUrl:
            "https://www.sligro.nl/image-service/_jcr_content.product.08712000048433.image/1/large.jpeg",
          businessId: 3,
          categoryId: 3,
          alcohoolRate: 5,
          size: 250,
          country: "Belgium",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10,
          title: "Chimay Rouge",
          description: "Sint quis ",
          imageUrl: "https://chimay.com/chimay-rouge/build/img/home-intro.jpg",
          businessId: 4,
          categoryId: 2,
          alcohoolRate: 5,
          size: 250,
          country: "Irland",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 11,
          title: "St Bernardus Abt 12",
          description: "Sint quis ",
          imageUrl:
            "https://static.ah.nl/dam/product/AHI_43545239353733343835?revLabel=22&rendition=800x800_JPG_Q90&fileType=binary",
          businessId: 4,
          categoryId: 3,
          alcohoolRate: 5,
          size: 250,
          country: "Irland",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 12,
          title: "Chimay Tripel",
          description: "Sint quis ",
          imageUrl:
            "https://www.biernet.nl/images/merken/77043-Chimay%20Tripel%20met%20een%20kaasje%20ernaast.jpg",
          businessId: 4,
          categoryId: 3,
          alcohoolRate: 5,
          size: 250,
          country: "Irland",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 13,
          title: "Rochefort 6",
          description: "Sint quis ",
          imageUrl:
            "https://cdn.webshopapp.com/shops/65337/files/84613613/trappistes-rochefort-6.jpg",
          businessId: 5,
          categoryId: 3,
          alcohoolRate: 5,
          size: 250,
          country: "Irland",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 14,
          title: "Rochefort 8",
          description: "Sint quis ",
          imageUrl:
            "https://cdn.webshopapp.com/shops/65337/files/84613574/trappistes-rochefort-8.jpg",
          businessId: 5,
          categoryId: 2,
          alcohoolRate: 5,
          size: 250,
          country: "Irland",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 15,
          title: "Rochefort 10",
          description: "Sint quis ",
          imageUrl:
            "https://beerstorexl.com/wp-content/uploads/2020/04/23290_rochefort_10_33cl.png",
          businessId: 5,
          categoryId: 2,
          alcohoolRate: 5,
          size: 250,
          country: "Irland",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("beers", null, {});
  },
};
